version: '3.9'

services:
  demo-ci4:
    image: php:8.1-apache
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  postgre-db:
    image: postgres:15
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    
volumes:
  db-data: